services:
    cent.refrigerator_bundle.cache_listener:
        class: Cent\RefrigeratorBundle\EventListener\CacheListener
        scope: request
        arguments: [ "@security.context" ]
        tags:
            - { name: "kernel.event_listener", event: "kernel.controller",  method: "onKernelController" }
